# Generated by Django 5.2 on 2025-04-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='generated_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
