# Generated by Django 5.2 on 2025-05-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0008_remove_grade_resit_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResitExamDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.PositiveIntegerField()),
                ('exam_type', models.CharField(choices=[('written', 'Written'), ('multiple_choice', 'Multiple Choice'), ('practical', 'Practical')], max_length=50)),
                ('calculator_allowed', models.BooleanField(default=False)),
                ('place_and_time', models.CharField(blank=True, max_length=100)),
                ('additional_notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resit_details', to='exams.course')),
            ],
        ),
    ]
