# Generated by Django 5.2 on 2025-05-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resitexamdetail',
            old_name='place_and_time',
            new_name='date',
        ),
        migrations.AddField(
            model_name='resitexamdetail',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resitexamdetail',
            name='exam_type',
            field=models.TextField(blank=True),
        ),
    ]
