# Generated by Django 5.2 on 2025-04-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resitgrade',
            old_name='grade',
            new_name='letter_grade',
        ),
        migrations.AddField(
            model_name='resitgrade',
            name='final_exam_grade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resitgrade',
            name='final_numeric_grade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resitgrade',
            name='midterm_grade',
            field=models.FloatField(default=0.0),
        ),
    ]
