# Generated by Django 5.2 on 2025-04-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_grade_resitgrade_letter_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resitgrade',
            name='final_numeric_grade',
        ),
        migrations.AddField(
            model_name='resitgrade',
            name='final_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resitgrade',
            name='final_exam_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resitgrade',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='resitgrade',
            name='midterm_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
