# Generated by Django 5.2 on 2025-04-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_resitgrade_final_numeric_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resitgrade',
            name='absences',
            field=models.IntegerField(default=0),
        ),
    ]
