# Generated by Django 5.2 on 2025-04-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_resitgrade_absences'),
    ]

    operations = [
        migrations.AddField(
            model_name='resitgrade',
            name='declared_resit',
            field=models.BooleanField(default=False),
        ),
    ]
