# Generated by Django 5.2 on 2025-04-30 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_resitgrade_declared_resit'),
        ('users', '0002_studentprofile_generated_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_grade', models.FloatField(blank=True, null=True)),
                ('final_exam_grade', models.FloatField(blank=True, null=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('letter_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('eligibility', models.CharField(max_length=50)),
                ('absences', models.IntegerField(default=0)),
                ('declared_resit', models.BooleanField(default=False)),
                ('resit_grade', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='ResitGrade',
        ),
    ]
