# Generated by Django 5.2 on 2025-04-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_grade_delete_resitgrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='resit_grade',
            new_name='resit_exam_grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='resit_final_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='resit_letter_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='resit_used',
            field=models.BooleanField(default=False),
        ),
    ]
