# Generated by Django 5.2 on 2025-05-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_rename_resit_grade_grade_resit_exam_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='resit_used',
        ),
    ]
